default:
	python pixel_from_coordinates.py --iters=2000 --n_fourier_features=0 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=2000 --n_fourier_features=8 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=2000 --n_fourier_features=16 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=3000 --n_fourier_features=32 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=3000 --n_fourier_features=64 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=5000 --n_fourier_features=128 --lr=0.1 --schedulefn="lambda x: 1"
	python pixel_from_coordinates.py --iters=5000 --n_fourier_features=256 --lr=0.1 --schedulefn="lambda x: 1"


pytorch:
	python pytorch_pixel_from_coordinates.py --iters=500 --n_fourier_features=0 --lr=2 --schedulefn="lambda x: 1"
	python pytorch_pixel_from_coordinates.py --iters=500 --n_fourier_features=8 --lr=2 --schedulefn="lambda x: 1"
	python pytorch_pixel_from_coordinates.py --iters=500 --n_fourier_features=16 --lr=2 --schedulefn="lambda x: 1"
	python pytorch_pixel_from_coordinates.py --iters=500 --n_fourier_features=32 --lr=5 --schedulefn="lambda x: 1"
	python pytorch_pixel_from_coordinates.py --iters=1000 --n_fourier_features=64 --lr=5 --schedulefn="lambda x: 1"
	python pytorch_pixel_from_coordinates.py --iters=1000 --n_fourier_features=128 --lr=1 --schedulefn="lambda x: 1"
 	
